# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: titan
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:

- task: NuGetToolInstaller@1
  displayName: Install Lastest Nuget

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '2ee62add-e34e-4fc0-aa13-bc3a8223e9b9'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: '$(solution)'
    arguments: '--configuration=$(buildConfiguration) /p:Platform="$(buildPlatform)"'

